### ISSUE TITLE
Game won't even compile

### ISSUE THREAD

**Issue by OmerFlame** [zkry/golang-tetris#1]
I used `go get` to copy the project to my hard drive, as well as the game engine. I tried running `go run *.go`, and it spit out an error:

`GetFileAttributesEx *.go: The filename, directory name, or volume label syntax is incorrect.`

After that, I tried running `go run main.go`, and it spit out ANOTHER error:

`# command-line-arguments
.\main.go:140:11: gameBoard.addPiece undefined (type Board has no field or method addPiece)
.\main.go:152:27: gameBoard.applyGravity undefined (type Board has no field or method applyGravity)
.\main.go:154:17: gameBoard.isTouchingFloor undefined (type Board has no field or method isTouchingFloor)
.\main.go:180:13: gameBoard.movePiece undefined (type Board has no field or method movePiece)
.\main.go:198:13: gameBoard.rotatePiece undefined (type Board has no field or method rotatePiece)
.\main.go:199:16: gameBoard.isTouchingFloor undefined (type Board has no field or method isTouchingFloor)
.\main.go:204:13: gameBoard.instafall undefined (type Board has no field or method instafall)
.\main.go:216:12: gameBoard.displayBoard undefined (type Board has no field or method displayBoard)
.\main.go:244:15: undefined: getShapeFromPiece
.\main.go:249:16: undefined: getShapeWidth
.\main.go:249:16: too many errors
`

Can I get help running the game? I'm trying to learn Go because of a personal project, and this can be a good example, though it doesn't work.

P.S: I tried running `go build`. It DID complete, though it stopped a fraction of a second after building, because it spit out a panic. I think this is a serious issue. Please help me!

**Comment by sijis** [comment]
I was also getting similar errors doing `go run main.go`, however, compiling did work and the game was playable.
```
$ go mod init github.com/zkry/golang-tetris
$ go build
$ ./golang-tetris
```

**Comment by zkry** [comment]
Sorry for such a delayed response. This was indeed a problem that got introduced when Go modules were introduced. I set up the project to work with Go modules now so running `go run .` should successfully start the game upon checking out the code.
